version: 2.1

orbs:
#  slack: circleci/slack@4.1
  tfsec: mycodeself/tfsec@1.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - tfsec/install:
          version: latest 
workflows:
  example-workflow:
    jobs:
      - example-job
