version: 2.1
orbs:
  tfsec: mycodeself/tfsec-orb@1.0.5
jobs:
  build:
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: which tfsec
      - run: tfsec .
#       - run: terraform plan
