version: 2.1

orbs:
#  slack: circleci/slack@4.1
  terraform: circleci/terraform@3.0.0
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
