version: 2

jobs:
  tfsec:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            hostname
            #terraform init -input=false
           # terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            ls
            pwd
            whoami
            hostname
            #terraform init -input=false
           # terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  tfsec:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
