version: 2.1

orbs:
#  slack: circleci/slack@4.1
  terraform: circleci/terraform@3.0.0
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: terraform init

workflows:
  analyze-tf-code:
    jobs:
      - single-job-lifecycle
