version: 2.1

orbs:
#  slack: circleci/slack@4.1
  tfsec: mycodeself/tfsec@1.1.0
jobs:
  single-job-lifecycle:
    executor: tfsec/default
    steps:
      - checkout
      - run: ls
      - run: which tfsec


workflows:
  analyze-tf-code:
    jobs:
      - single-job-lifecycle
