version: 2.1
executors:
  terraform:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
jobs:
  plan:
    executor: terraform
    parameters:
      tfenv:
        type: string
        default: non
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: terraform init
#      - <<: *persist
